### ISSUE TITLE
request to move repo under fonttools organization

### ISSUE THREAD

**Issue by anthrotype** [fonttools/unicodedata2#43]
Hi @mikekap
would you be willing to share the maintenance burden with us by moving the repository under the [fonttools](https://github.com/fonttools) organization?
We use your project in our open-source font build pipeline, and are interested in keeping it up to date with the latest Unicode versions as they get published upstream.
We would like to switch from Travis/Appveyor to Github Workflows and it makes things easier when developers can access the repository settings (e.g. for things like setting encrypted token in the repository's secrets to be able to upload wheels to PyPI).
Of course you will be continue to be the main admin and won't lose control of the project.
Let us know what you think,
thanks

/cc @madig

**Comment by mikekap** [comment]
Happy to do that - I clearly don't have the time to be a good maintainer nowadays. I'll need permissions in the fonttools organization to transfer the repo there - just attempting to transfer the project now results in "You don’t have the permission to create public repositories on fonttools".

Separately, I disabled the travis CI check so PRs can merge here in the meantime.

**Comment by anthrotype** [comment]
Thank you Mike! I just sent you the invite to join the organisation.
