### ISSUE TITLE
add script data

### ISSUE THREAD

**Issue by eroux** [fonttools/unicodedata2#57]
Hi, thanks a lot for this wonderful and very useful code!

My main interest is to get the script for a character through UAX#24 (http://www.unicode.org/Public/UNIDATA/Scripts.txt), is it something that could be added? Thanks!

**Comment by anthrotype** [comment]
Hi, this is meant to be only a backport of the cpython's built-in `unicodedata` module, we don't add new features that are not in the upstream copy.
If you're interested in obtaining the script for a unicode character, try using `fontTools.unicodedata::script` method, i.e.:
https://github.com/fonttools/fonttools/blob/a2eef358be401cfa1c783f24f48a000424457152/Lib/fontTools/unicodedata/__init__.py#L45

The `fontTools.unicodedata` module works like a shim to the built-in `unicodedata` (or `unicodedata2` if available) and adds a few more additional methods, like this `script` method:

```python
>>> from fontTools import unicodedata
>>> unicodedata.script(chr(0x6AD))
'Arab'
```

**Comment by eroux** [comment]
thanks for your answer, I perfectly understand! I'll look at fontTools

Just for reference, there's a zombie issue for the addition of script to `unicodedata` in cpython on https://github.com/python/cpython/issues/50580
